apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-rolebinding
  namespace: dv   # Change this to the appropriate namespace if needed
subjects:
- kind: ServiceAccount
  name: jenkins  # The name of your service account
  namespace: dv   # The namespace of your service account
roleRef:
  kind: Role
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io


