apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods", "deployments", "services", "configmaps"]  # Modify as needed
  verbs: ["get", "list", "create", "update", "delete"]  # Modify as needed
